name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Hello world action
      with: # Set the secret as an input
        super_secret: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
